"""Motion tracking environments."""

__unilab_registry_modules__ = (
    "unilab.envs.motion_tracking.g1",
    "unilab.envs.motion_tracking.x2",
)

from .g1 import (
    BoxMotionData,
    BoxMotionLoader,
    G1BoxTracking23DofCfg,
    G1BoxTracking23DofEnvCfg,
    G1BoxTrackingCfg,
    G1BoxTrackingEnv,
    G1BoxTrackingEnvCfg,
    G1ClimbTrackingCfg,
    G1ClimbTrackingEnv,
    G1ClimbTrackingEnvCfg,
    G1FlipTracking23DofCfg,
    G1FlipTracking23DofEnvCfg,
    G1FlipTrackingCfg,
    G1FlipTrackingEnv,
    G1FlipTrackingEnvCfg,
    G1FlipTrackingSAC23DofCfg,
    G1FlipTrackingSAC23DofEnv,
    G1MotionTracking23DofCfg,
    G1MotionTracking23DofDeployEnvCfg,
    G1MotionTracking23DofEnvCfg,
    G1MotionTrackingCfg,
    G1MotionTrackingEnv,
    G1MotionTrackingEnvCfg,
    G1MotionTrackingSAC23DofCfg,
    G1MotionTrackingSAC23DofEnv,
    G1MotionTrackingSACCfg,
    G1MotionTrackingSACEnv,
    G1WallFlipTracking23DofCfg,
    G1WallFlipTracking23DofEnvCfg,
    G1WallFlipTrackingCfg,
    G1WallFlipTrackingEnv,
    G1WallFlipTrackingEnvCfg,
    G1WallFlipTrackingSAC23DofCfg,
    G1WallFlipTrackingSAC23DofEnv,
    G1WBTObs23DofCfg,
    G1WBTObsCfg,
    G1WBTObsEnv,
)
from .x2 import (
    X2MotionTrackingCfg,
    X2WallFlipTrackingCfg,
    X2WallFlipTrackingEnv,
    X2WallFlipTrackingEnvCfg,
)

__all__ = [
    "G1MotionTrackingCfg",
    "G1MotionTrackingEnv",
    "G1MotionTrackingEnvCfg",
    "G1MotionTrackingSACCfg",
    "G1MotionTrackingSACEnv",
    "G1WBTObsCfg",
    "G1WBTObsEnv",
    "G1FlipTrackingCfg",
    "G1FlipTrackingEnv",
    "G1FlipTrackingEnvCfg",
    "G1WallFlipTrackingCfg",
    "G1WallFlipTrackingEnv",
    "G1WallFlipTrackingEnvCfg",
    "G1ClimbTrackingCfg",
    "G1ClimbTrackingEnv",
    "G1ClimbTrackingEnvCfg",
    "G1BoxTrackingCfg",
    "G1BoxTrackingEnv",
    "G1BoxTrackingEnvCfg",
    "BoxMotionData",
    "BoxMotionLoader",
    "X2MotionTrackingCfg",
    "X2WallFlipTrackingCfg",
    "X2WallFlipTrackingEnv",
    "X2WallFlipTrackingEnvCfg",
    # 23-DoF variants (from parent UniLab/, under testing)
    "G1MotionTracking23DofCfg",
    "G1MotionTracking23DofDeployEnvCfg",
    "G1MotionTracking23DofEnvCfg",
    "G1MotionTrackingSAC23DofCfg",
    "G1MotionTrackingSAC23DofEnv",
    "G1WBTObs23DofCfg",
    "G1FlipTracking23DofCfg",
    "G1FlipTracking23DofEnvCfg",
    "G1FlipTrackingSAC23DofCfg",
    "G1FlipTrackingSAC23DofEnv",
    "G1WallFlipTracking23DofCfg",
    "G1WallFlipTracking23DofEnvCfg",
    "G1WallFlipTrackingSAC23DofCfg",
    "G1WallFlipTrackingSAC23DofEnv",
    "G1BoxTracking23DofCfg",
    "G1BoxTracking23DofEnvCfg",
]
