"""Reusable actuator-level numeric contracts."""

from unilab.actuators.dm_j4340p_v1 import (
    DMJ4340PV10LossThermalProxy,
    DMJ4340PV10MotorSpec,
    SharedDCBusConfig,
)
from unilab.actuators.gf43x import (
    GF43_MOTOR_SPECS,
    GF43X10_10,
    GF43X40_10,
    GF43X40_10_EMPTY_LOAD_FIT,
    GF43X40_10_MAX_OBSERVED_OUTPUT_SPEED_RAD_S,
    GF43X40_10_MOTORING_SPEED_RAD_S,
    GF43X40_10_MOTORING_TORQUE_NM,
    GF43ActuatorResponseFit,
    GF43BenchPoint,
    GF43EmptyLoadFit,
    GF43MotorSpec,
    StaticOperatingPointAssessment,
    assess_static_operating_point,
    gf43x40_motoring_torque_limit,
    gf43x40_torque_bounds,
    interpolate_bench_point_by_torque,
    mechanical_power_w,
    rad_s_to_rpm,
    rpm_to_rad_s,
    static_torque_magnitude_limit,
)

__all__ = [
    "DMJ4340PV10LossThermalProxy",
    "DMJ4340PV10MotorSpec",
    "GF43_MOTOR_SPECS",
    "GF43ActuatorResponseFit",
    "GF43BenchPoint",
    "GF43EmptyLoadFit",
    "GF43MotorSpec",
    "GF43X10_10",
    "GF43X40_10",
    "GF43X40_10_EMPTY_LOAD_FIT",
    "GF43X40_10_MAX_OBSERVED_OUTPUT_SPEED_RAD_S",
    "GF43X40_10_MOTORING_SPEED_RAD_S",
    "GF43X40_10_MOTORING_TORQUE_NM",
    "SharedDCBusConfig",
    "StaticOperatingPointAssessment",
    "assess_static_operating_point",
    "gf43x40_motoring_torque_limit",
    "gf43x40_torque_bounds",
    "interpolate_bench_point_by_torque",
    "mechanical_power_w",
    "rad_s_to_rpm",
    "rpm_to_rad_s",
    "static_torque_magnitude_limit",
]
